# Book title
title: "The Predicting Pulsed-Laser Deposition SrTiO3 Homoepitaxy Growth Dynamics using High-Speed Reflection High-Energy Electron Diffraction"
copyright: "2025" # Copyright year to be placed in the footer
logo: ./_static/Drexel_blue_Logo_square_Light.png # A path to the book logo for light mode

authors:
  - name: "Yichen Guo"
  - name: "Peter Meisenheimer"
  - name: "Shuyu Qin"
  - name: "Xinqiao Zhang"
  - name: "Julian Goddy"
  - name: "Ramamoorthy Ramesh"
  - name: "Lane W. Martin"
  - name: "Joshua C. Agar"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  timeout: 600

# Book language
language: "en"

# Launch buttons (optional)
launch_buttons:
  colab_url: "https://colab.research.google.com/"
  github_url: "https://github.com/m3-learning/Predicting-Pulsed-Laser-Deposition-SrTiO3-Homoepitaxy-Growth-Dynamics-using-RHEED"

repository:
  url: "https://github.com/m3-learning/Predicting-Pulsed-Laser-Deposition-SrTiO3-Homoepitaxy-Growth-Dynamics-using-RHEED"

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  static_path:
    - _static
  css:
    - theme.css
  logo: