# Book title
title: "The Predicting Pulsed-Laser Deposition SrTiO3 Homoepitaxy Growth Dynamics using High-Speed Reflection High-Energy Electron Diffraction"

authors:
  - name: "Yichen Guo"
  - name: "Peter Meisenheimer"
  - name: "Shuyu Qin"
  - name: "Xinqiao Zhang"
  - name: "Julian Goddy"
  - name: "Ramamoorthy Ramesh"
  - name: "Lane W. Martin"
  - name: "Joshua C. Agar"


# Book language
language: "en"

# Launch buttons (optional)
launch_buttons:
  colab_url: "https://colab.research.google.com/"
  binderhub_url: "https://mybinder.org"
  notebook_interface: "classic"
  github_url: "https://github.com/M3-Learning-Experiments/Predicting-Pulsed-Laser-Deposition-SrTiO3-Homoepitaxy-Growth-Dynamics-using-RHEED.git"

repository:
  url: "https://github.com/M3-Learning-Experiments/Predicting-Pulsed-Laser-Deposition-SrTiO3-Homoepitaxy-Growth-Dynamics-using-RHEED.git"
