name: deploy-book

on:
  push:
    branches:
      - main # Adjust branch name if necessary

env:
  BASE_URL: /${{ github.event.repository.name }}

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-book:
    if: |
      github.repository == 'm3-learning/Predicting-Pulsed-Laser-Deposition-SrTiO3-Homoepitaxy-Growth-Dynamics-using-RHEED' &&
      contains(github.event.head_commit.message, '#push')
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Install Conda
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -qO- https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh > miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          export PATH="$HOME/miniconda/bin:$PATH"
          conda init bash

      - name: Create and Activate Conda Environment
        shell: bash -l {0}
        run: |
          source $HOME/.bashrc
          conda create -n book python=3.11 -y
          conda activate book
          conda install -c conda-forge mayavi -y

      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          source $HOME/.bashrc
          conda activate book
          pip install -r requirements.txt

      - name: Build the book
        shell: bash -l {0}
        run: |
          source $HOME/.bashrc
          conda activate book
          rm -rf ./book/_build
          jupyter-book build ./book

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          publish_dir: ./book/_build/html
